### ISSUE TITLE
marconi error

### ISSUE THREAD

**Issue by albz** [ALaDyn/ALaDyn#25]
https://github.com/ALaDyn/ALaDyn/blob/6659c053ce270de36858aac14fa1b673f83d4858/src/pdf_moments.f90#L418

On Marconi I have an issue here, where emittance returns NaN instead of the nominal value. I do not have such an issue on cnaf (for example). I am wondering if I need a blocking command to synch all processors before calculation. But all the variable should be know by now and no issue is expected.

**Comment by cenit** [comment]
is this issue still valid? Shall we close it?

**Comment by albz** [comment]
yup, close it. I solved it, still I need to clean the code in these sections
