### ISSUE TITLE
Aladyn vs Epoch  PIC code

### ISSUE THREAD

**Issue by dsbertini** [ALaDyn/ALaDyn#30]
Hi,

I would like to know the advantages/difference between the well known Epoch PIC code and AlaDyn 
concerning for simulation of Laser Ion Acceleration via TNSA. 

Looking at the docs you provide, Aladyn seems to be tailored/optimized for such kind of simulation?

Thanks in advance.

Denis Bertini

**Comment by cenit** [comment]
Hi @dsbertini,
any discussion between two different PIC codes, one of which is completely out of our control, is beyond the scope of a GitHub repository issue. Please feel free anyway to ask question regarding ALaDyn here.

**Comment by albz** [comment]
Hi @dsbertini, you opened an 'issue' on github. This is not a computational issue, more like an enquire. Please feel free to contact any of the main authors if you are willing to use the code for your research.
