### ISSUE TITLE
Cmake issue with some strings

### ISSUE THREAD

**Issue by titoiride** [ALaDyn/ALaDyn#44]
Version 2.8.12.2 of CMAKE (e.g. cmake@CNAF) result in some error with the CMakeLists.txt, such as

`CMake Error at CMakeLists.txt:47 (string):
  string does not recognize sub-command APPEND`.

Version 3.5.2 works.

**Comment by cenit** [comment]
cmake minimim version must be upgraded to CMake 3.4
To have it working on hpc@CNAF please upgrade your path, since last update the path of CMake Module is changed
