### ISSUE TITLE
CI failures on Mac when using mpich

### ISSUE THREAD

**Issue by cenit** [ALaDyn/ALaDyn#58]
Due to https://github.com/Homebrew/homebrew-core/pull/36265, unfortunately now the combination mac+fftw+mpich is broken.
We should consider moving those combinations to allowed failures or even removing them

**Comment by titoiride** [comment]
For now, I would add them to the allowed failures, waiting for a possible fix from homebrew (?) or a future ALaDyn version with optional fftw.

**Comment by cenit** [comment]
I implemented the allow_failure workaround in #61
